---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-httpd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-httpd
  template:
    metadata:
      labels:
        app: app-httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
          resources:
            requests:         # Minimum guaranteed resources
              cpu: "100m"     # 0.1 CPU
              memory: "128Mi" # 128 MiB RAM
            limits:           # Maximum resources allowed
              cpu: "500m"     # 0.5 CPU
              memory: "256Mi" # 256 MiB RAM