apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application
  namespace: argocd   # must be the same namespace where ArgoCD is installed
spec:
  project: default
  source:
    repoURL: http://192.168.0.115/mohammed.zuhair/nginx-deployment-example.git
    targetRevision: HEAD   # can be a branch, tag, or commit
    path: dev        # folder inside repo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:             # auto-sync enabled
      prune: true          # delete resources not in Git
      selfHeal: true       # auto-correct drift
    syncOptions:
    - CreateNamespace=true # create namespace if missing
